-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  user_id uuid NOT NULL,
  phone text,
  address text,
  instagram text,
  twitter text,
  facebook text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text,
  liked_properties jsonb DEFAULT '[]'::jsonb,
  profession text,
  siret text,
  CONSTRAINT profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  phone_number text,
  contact_email text,
  instagram_handle text,
  facebook_url text,
  twitter_handle text,
  reference_number text,
  cadastral_code text,
  title text NOT NULL,
  description text,
  price numeric NOT NULL,
  currency text DEFAULT 'EUR'::text,
  m2 numeric,
  beds integer DEFAULT 0,
  baths integer DEFAULT 0,
  rooms integer,
  year_built integer,
  condition text,
  status text,
  featured boolean DEFAULT false,
  terrace_area numeric,
  kitchen_type text,
  ceiling_height numeric,
  floor_level integer,
  total_floors integer,
  amenities ARRAY DEFAULT '{}'::text[],
  equipment ARRAY DEFAULT '{}'::text[],
  internet_tv ARRAY DEFAULT '{}'::text[],
  storage ARRAY DEFAULT '{}'::text[],
  security ARRAY DEFAULT '{}'::text[],
  nearby_places ARRAY DEFAULT '{}'::text[],
  online_services ARRAY DEFAULT '{}'::text[],
  has_elevator boolean DEFAULT false,
  has_ventilation boolean DEFAULT false,
  has_air_conditioning boolean DEFAULT false,
  is_accessible boolean DEFAULT false,
  has_gas boolean DEFAULT false,
  has_loggia boolean DEFAULT false,
  has_fireplace boolean DEFAULT false,
  has_internet boolean DEFAULT false,
  has_cable_tv boolean DEFAULT false,
  has_satellite_tv boolean DEFAULT false,
  has_phone_line boolean DEFAULT false,
  has_vent boolean DEFAULT false,
  has_cinema boolean DEFAULT false,
  has_dishwasher boolean DEFAULT false,
  has_gas_stove boolean DEFAULT false,
  has_electric_kettle boolean DEFAULT false,
  has_induction_oven boolean DEFAULT false,
  has_microwave boolean DEFAULT false,
  has_electric_oven boolean DEFAULT false,
  has_washing_machine boolean DEFAULT false,
  has_tv boolean DEFAULT false,
  has_coffee_machine boolean DEFAULT false,
  has_audio_system boolean DEFAULT false,
  has_heater boolean DEFAULT false,
  has_hair_dryer boolean DEFAULT false,
  has_refrigerator boolean DEFAULT false,
  has_vacuum_cleaner boolean DEFAULT false,
  has_dryer boolean DEFAULT false,
  has_iron boolean DEFAULT false,
  has_co_detector boolean DEFAULT false,
  has_smoke_detector boolean DEFAULT false,
  has_evacuation_ladder boolean DEFAULT false,
  has_fire_fighting_system boolean DEFAULT false,
  has_perimeter_cameras boolean DEFAULT false,
  has_alarm boolean DEFAULT false,
  has_live_protection boolean DEFAULT false,
  has_locked_entrance boolean DEFAULT false,
  has_locked_yard boolean DEFAULT false,
  near_bus_stop boolean DEFAULT false,
  near_bank boolean DEFAULT false,
  near_subway boolean DEFAULT false,
  near_supermarket boolean DEFAULT false,
  near_kindergarten boolean DEFAULT false,
  near_city_center boolean DEFAULT false,
  near_pharmacy boolean DEFAULT false,
  near_greenery boolean DEFAULT false,
  near_park boolean DEFAULT false,
  near_shopping_centre boolean DEFAULT false,
  near_school boolean DEFAULT false,
  near_old_district boolean DEFAULT false,
  allows_pets boolean DEFAULT false,
  allows_parties boolean DEFAULT false,
  allows_smoking boolean DEFAULT false,
  building_material text,
  furniture_type text,
  storeroom_type text,
  heating_type text,
  hot_water_type text,
  parking_type text,
  address_street text,
  address_city text,
  address_district text,
  lat numeric DEFAULT 41.7151,
  lng numeric DEFAULT 44.8271,
  images ARRAY DEFAULT '{}'::text[],
  property_type text,
  listing_type text,
  plan text,
  agent_name text,
  agent_phone text,
  project_name text,
  price_per_m2 numeric,
  frais_agence numeric,
  charges_mensuelles numeric,
  taxe_fonciere numeric,
  dpe_classe_energie text,
  dpe_consommation integer,
  ges_classe_gaz text,
  ges_emission integer,
  nom_agence text,
  reference_annonce text,
  nombre_photos integer DEFAULT 0,
  lien_visite_virtuelle text,
  date_publication timestamp with time zone,
  date_mise_a_jour timestamp with time zone,
  code_postal text,
  surface_balcon_terrasse numeric,
  parking_box integer,
  cave boolean DEFAULT false,
  nombre_etages_immeuble integer,
  annee_construction integer,
  CONSTRAINT properties_pkey PRIMARY KEY (id),
  CONSTRAINT properties_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.property_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id uuid,
  image_url text NOT NULL,
  is_primary boolean DEFAULT false,
  CONSTRAINT property_images_pkey PRIMARY KEY (id),
  CONSTRAINT property_images_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id)
);